/**
 * AUREA HOTEL — Mock Data
 * 
 * This provides realistic data for development before Supabase is connected.
 * Once Supabase is configured, these will be replaced by actual DB queries.
 */

// ── Room Types ──
export const ROOM_TYPES = [
  {
    id: 'rt-standard',
    name: 'Standard Room',
    slug: 'standard-room',
    description: 'Nuestra habitación Standard ofrece todo lo necesario para una estancia confortable. Decorada con un estilo moderno y elegante, cuenta con una cama Queen de alta calidad, baño privado con amenidades premium, y todas las comodidades que esperarías de un hotel de primera categoría.',
    base_price: 119,
    capacity: 2,
    size: 28,
    beds: '1 cama Queen',
    image_url: '/images/rooms/standard.jpg',
    is_active: true,
    amenities: ['Wi-Fi', 'TV', 'Aire acondicionado', 'Baño privado', 'Caja fuerte', 'Secador de pelo'],
    rating: 4.5,
    review_count: 24,
  },
  {
    id: 'rt-deluxe',
    name: 'Deluxe Room',
    slug: 'deluxe-room',
    description: 'La Deluxe Room eleva la experiencia con espacios más amplios y detalles premium. Disfruta de una lujosa cama King, minibar completo, y un ambiente diseñado para el máximo confort. Perfecta para parejas que buscan algo especial.',
    base_price: 149,
    capacity: 2,
    size: 32,
    beds: '1 cama King',
    image_url: '/images/rooms/deluxe.jpg',
    is_active: true,
    amenities: ['Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones'],
    rating: 4.7,
    review_count: 38,
  },
  {
    id: 'rt-suite',
    name: 'Suite Ocean View',
    slug: 'suite-ocean-view',
    description: 'Nuestra Suite Ocean View es la definición del lujo costero. Con amplias ventanas panorámicas que enmarcan el océano, una sala de estar independiente, y un balcón privado, cada momento se convierte en una experiencia inolvidable. Incluye cama King y sofá cama para mayor versatilidad.',
    base_price: 249,
    capacity: 3,
    size: 48,
    beds: '1 cama King + sofá cama',
    image_url: '/images/rooms/suite.jpg',
    is_active: true,
    amenities: ['Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Balcón', 'Vista al mar', 'Sala de estar', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones'],
    rating: 4.9,
    review_count: 52,
  },
  {
    id: 'rt-presidential',
    name: 'Presidential Suite',
    slug: 'presidential-suite',
    description: 'La Presidential Suite es nuestra joya de la corona. Con 75 m² de puro lujo, dos dormitorios con camas King, un elegante salón, jacuzzi privado con vista al mar, y servicio de mayordomo exclusivo. Una experiencia reservada para quienes no aceptan nada menos que lo extraordinario.',
    base_price: 449,
    capacity: 4,
    size: 75,
    beds: '2 camas King',
    image_url: '/images/rooms/presidential.jpg',
    is_active: true,
    amenities: ['Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Balcón', 'Vista al mar', 'Jacuzzi', 'Sala de estar', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones'],
    rating: 5.0,
    review_count: 15,
  },
];

// ── Physical Rooms ──
export const ROOMS = [
  { id: 'r-101', room_type_id: 'rt-standard', room_number: '101', floor: 1, status: 'available' },
  { id: 'r-102', room_type_id: 'rt-standard', room_number: '102', floor: 1, status: 'available' },
  { id: 'r-103', room_type_id: 'rt-standard', room_number: '103', floor: 1, status: 'available' },
  { id: 'r-104', room_type_id: 'rt-standard', room_number: '104', floor: 1, status: 'maintenance' },
  { id: 'r-201', room_type_id: 'rt-deluxe', room_number: '201', floor: 2, status: 'available' },
  { id: 'r-202', room_type_id: 'rt-deluxe', room_number: '202', floor: 2, status: 'available' },
  { id: 'r-203', room_type_id: 'rt-deluxe', room_number: '203', floor: 2, status: 'available' },
  { id: 'r-204', room_type_id: 'rt-deluxe', room_number: '204', floor: 2, status: 'available' },
  { id: 'r-301', room_type_id: 'rt-suite', room_number: '301', floor: 3, status: 'available' },
  { id: 'r-302', room_type_id: 'rt-suite', room_number: '302', floor: 3, status: 'available' },
  { id: 'r-303', room_type_id: 'rt-suite', room_number: '303', floor: 3, status: 'available' },
  { id: 'r-304', room_type_id: 'rt-suite', room_number: '304', floor: 3, status: 'available' },
  { id: 'r-401', room_type_id: 'rt-presidential', room_number: '401', floor: 4, status: 'available' },
  { id: 'r-402', room_type_id: 'rt-presidential', room_number: '402', floor: 4, status: 'available' },
  { id: 'r-403', room_type_id: 'rt-presidential', room_number: '403', floor: 4, status: 'available' },
  { id: 'r-404', room_type_id: 'rt-presidential', room_number: '404', floor: 4, status: 'available' },
];

// ── Sample Reservations ──
export const SAMPLE_RESERVATIONS = [
  {
    id: 'res-1',
    reservation_code: 'AUR-1042',
    user_id: 'user-1',
    room_id: 'r-201',
    room_number: '201',
    room_type: 'Deluxe Room',
    check_in: '2026-08-15',
    check_out: '2026-08-18',
    adults: 2,
    children: 0,
    status: 'confirmed',
    total_amount: 623.70,
    tax_amount: 56.70,
    special_requests: 'Habitación alejada del ascensor',
    created_at: '2026-08-01T10:00:00Z',
    guest: { full_name: 'Jesús Figueroa', email: 'jesus@example.com', phone: '+1234567890', country: 'México' },
    payment: { status: 'paid', paypal_order_id: 'PP-12345', amount: 623.70 },
  },
  {
    id: 'res-2',
    reservation_code: 'AUR-1043',
    user_id: 'user-2',
    room_id: 'r-301',
    room_number: '301',
    room_type: 'Suite Ocean View',
    check_in: '2026-08-10',
    check_out: '2026-08-14',
    adults: 2,
    children: 1,
    status: 'checked_in',
    total_amount: 1097.60,
    tax_amount: 99.60,
    special_requests: '',
    created_at: '2026-07-28T14:30:00Z',
    guest: { full_name: 'María López', email: 'maria@example.com', phone: '+0987654321', country: 'España' },
    payment: { status: 'paid', paypal_order_id: 'PP-12346', amount: 1097.60 },
  },
  {
    id: 'res-3',
    reservation_code: 'AUR-1044',
    user_id: 'user-3',
    room_id: 'r-401',
    room_number: '401',
    room_type: 'Presidential Suite',
    check_in: '2026-08-12',
    check_out: '2026-08-16',
    adults: 2,
    children: 0,
    status: 'confirmed',
    total_amount: 1975.60,
    tax_amount: 179.60,
    special_requests: 'Champagne en la habitación',
    created_at: '2026-08-05T09:15:00Z',
    guest: { full_name: 'Carlos Mendoza', email: 'carlos@example.com', phone: '+1122334455', country: 'Colombia' },
    payment: { status: 'paid', paypal_order_id: 'PP-12347', amount: 1975.60 },
  },
];

// ── Sample Reviews ──
export const SAMPLE_REVIEWS = [
  {
    id: 'rev-1',
    user_name: 'Ana García',
    room_type: 'Deluxe Room',
    rating: 5,
    comment: 'Una experiencia increíble. La habitación era perfecta, limpia y muy bien decorada. El personal fue extremadamente amable y atento. Sin duda volveré.',
    created_at: '2026-07-20T10:00:00Z',
    avatar_url: null,
    verified: true,
  },
  {
    id: 'rev-2',
    user_name: 'Roberto Martínez',
    room_type: 'Suite Ocean View',
    rating: 5,
    comment: 'La vista al mar desde la suite es espectacular. Nos despertamos cada mañana con un amanecer increíble. El desayuno incluido fue de primera calidad.',
    created_at: '2026-07-15T14:30:00Z',
    avatar_url: null,
    verified: true,
  },
  {
    id: 'rev-3',
    user_name: 'Laura Sánchez',
    room_type: 'Standard Room',
    rating: 4,
    comment: 'Muy buena relación calidad-precio. La habitación era cómoda y tenía todo lo necesario. El Wi-Fi funcionaba perfectamente. Recomendado.',
    created_at: '2026-07-10T08:00:00Z',
    avatar_url: null,
    verified: true,
  },
  {
    id: 'rev-4',
    user_name: 'Diego Torres',
    room_type: 'Presidential Suite',
    rating: 5,
    comment: 'Simplemente perfecto. El jacuzzi con vista al mar es una experiencia que no tiene precio. El servicio de mayordomo hizo nuestra estancia aún más especial.',
    created_at: '2026-07-05T18:00:00Z',
    avatar_url: null,
    verified: true,
  },
  {
    id: 'rev-5',
    user_name: 'Patricia Velásquez',
    room_type: 'Deluxe Room',
    rating: 4,
    comment: 'Excelente hotel. Las instalaciones del spa son maravillosas y la piscina es increíble. La única mejora sería más opciones en el menú del restaurante.',
    created_at: '2026-06-28T12:00:00Z',
    avatar_url: null,
    verified: true,
  },
  {
    id: 'rev-6',
    user_name: 'Fernando Ruiz',
    room_type: 'Suite Ocean View',
    rating: 5,
    comment: 'Celebramos nuestro aniversario aquí y fue una decisión perfecta. El hotel organizó una sorpresa especial en la habitación. Atención de primera.',
    created_at: '2026-06-20T16:00:00Z',
    avatar_url: null,
    verified: true,
  },
];

// ── Experiences ──
export const EXPERIENCES = [
  {
    id: 'exp-restaurant',
    name: 'Restaurante',
    description: 'Gastronomía de autor con ingredientes locales',
    image_url: '/images/experiences/restaurant.jpg',
  },
  {
    id: 'exp-spa',
    name: 'Spa',
    description: 'Tratamientos de bienestar y relajación total',
    image_url: '/images/experiences/spa.jpg',
  },
  {
    id: 'exp-pool',
    name: 'Piscina',
    description: 'Piscina infinity con vista panorámica al océano',
    image_url: '/images/experiences/pool.jpg',
  },
  {
    id: 'exp-gym',
    name: 'Gimnasio',
    description: 'Equipamiento de última generación 24/7',
    image_url: '/images/experiences/gym.jpg',
  },
];

// ── Features (Why Aurea) ──
export const FEATURES = [
  { icon: 'Wifi', title: 'Wi-Fi gratuito', description: 'Conexión de alta velocidad en todas las áreas del hotel' },
  { icon: 'Coffee', title: 'Desayuno incluido', description: 'Buffet gourmet con opciones internacionales cada mañana' },
  { icon: 'Clock', title: 'Atención 24/7', description: 'Nuestro equipo está disponible para ti en todo momento' },
  { icon: 'ShieldCheck', title: 'Cancelación flexible', description: 'Cancela hasta 24 horas antes sin cargos adicionales' },
];

// ── Amenity Icons mapping ──
export const AMENITY_ICONS = {
  'Wi-Fi': 'Wifi',
  'TV': 'Tv',
  'Minibar': 'Wine',
  'Aire acondicionado': 'Snowflake',
  'Baño privado': 'Bath',
  'Balcón': 'DoorOpen',
  'Vista al mar': 'Waves',
  'Jacuzzi': 'Droplets',
  'Sala de estar': 'Sofa',
  'Caja fuerte': 'Lock',
  'Secador de pelo': 'Wind',
  'Servicio de habitaciones': 'ConciergeBell',
  'Piscina': 'Waves',
};
