-- ============================================
-- AUREA HOTEL — PostgreSQL Database Schema
-- ============================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS btree_gist;  -- Needed for exclusion constraints
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; -- Needed for UUID generation

-- Drop existing tables/views if they exist (for easy re-running)
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS reservation_guests CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS room_images CASCADE;
DROP TABLE IF EXISTS room_type_amenities CASCADE;
DROP TABLE IF EXISTS amenities CASCADE;
DROP TABLE IF EXISTS room_types CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS hotel_settings CASCADE;

-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  country TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Room Types Table
CREATE TABLE room_types (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  base_price NUMERIC(10,2) NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 2,
  size NUMERIC(5,1),        -- m²
  beds TEXT,                 -- "1 cama King", "2 camas Queen"
  image_url TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Amenities Table
CREATE TABLE amenities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  icon TEXT,                  -- Lucide icon name
  category TEXT DEFAULT 'general',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Room Type Amenities (Join Table)
CREATE TABLE room_type_amenities (
  room_type_id UUID REFERENCES room_types(id) ON DELETE CASCADE,
  amenity_id UUID REFERENCES amenities(id) ON DELETE CASCADE,
  PRIMARY KEY (room_type_id, amenity_id)
);

-- 5. Rooms (Physical Rooms) Table
CREATE TABLE rooms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_type_id UUID NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
  room_number TEXT NOT NULL UNIQUE,
  floor INTEGER,
  status TEXT NOT NULL DEFAULT 'available'
    CHECK (status IN ('available', 'maintenance', 'inactive')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Room Images Table
CREATE TABLE room_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_type_id UUID NOT NULL REFERENCES room_types(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  alt_text TEXT,
  is_primary BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Reservations Table (With Exclusion Constraints)
CREATE TABLE reservations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reservation_code TEXT UNIQUE,          -- Format: AUR-XXXX (Generated by Trigger)
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  -- Generate stay_range automatically for overlap check (exclude last day for checkout checkin overlap)
  stay_range DATERANGE GENERATED ALWAYS AS (daterange(check_in, check_out, '[)')) STORED,
  adults INTEGER NOT NULL DEFAULT 1,
  children INTEGER DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled')),
  total_amount NUMERIC(10,2) NOT NULL,
  tax_amount NUMERIC(10,2) DEFAULT 0,
  special_requests TEXT,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  
  -- Prevent overlapping bookings for the same physical room unless the reservation is cancelled
  EXCLUDE USING GIST (
    room_id WITH =,
    stay_range WITH &&
  ) WHERE (status != 'cancelled'),
  
  CHECK (check_out > check_in)
);

-- 8. Reservation Guests Table
CREATE TABLE reservation_guests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  country TEXT,
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 9. Payments Table
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
  paypal_order_id TEXT,
  paypal_capture_id TEXT,
  amount NUMERIC(10,2) NOT NULL,
  currency TEXT DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 10. Reviews Table
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  room_type_id UUID NOT NULL REFERENCES room_types(id) ON DELETE CASCADE,
  reservation_id UUID NOT NULL UNIQUE REFERENCES reservations(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  is_visible BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 11. Hotel Settings Table
CREATE TABLE hotel_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT now()
);


-- ============================================
-- FUNCTIONS AND TRIGGERS
-- ============================================

-- Function to check if a user is an admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Trigger to automatically create a profile after signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- Trigger to generate a readable reservation code (e.g., AUR-1042) on insert
CREATE OR REPLACE FUNCTION generate_reservation_code()
RETURNS TRIGGER AS $$
DECLARE
  seq INTEGER;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(reservation_code FROM 5) AS INTEGER)), 999) + 1
  INTO seq FROM reservations;
  NEW.reservation_code := 'AUR-' || LPAD(seq::TEXT, 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER set_reservation_code
  BEFORE INSERT ON reservations
  FOR EACH ROW
  WHEN (NEW.reservation_code IS NULL)
  EXECUTE FUNCTION generate_reservation_code();


-- Function to check availability for frontend query
CREATE OR REPLACE FUNCTION check_room_availability(
  p_room_type_id UUID,
  p_check_in DATE,
  p_check_out DATE,
  p_guests INTEGER DEFAULT 1
)
RETURNS TABLE (
  room_id UUID,
  room_number TEXT,
  floor INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT r.id, r.room_number, r.floor
  FROM rooms r
  JOIN room_types rt ON r.room_type_id = rt.id
  WHERE r.room_type_id = p_room_type_id
    AND r.status = 'available'
    AND rt.capacity >= p_guests
    AND NOT EXISTS (
      SELECT 1 FROM reservations res
      WHERE res.room_id = r.id
        AND res.status NOT IN ('cancelled')
        AND res.stay_range && daterange(p_check_in, p_check_out, '[)')
    )
  ORDER BY r.room_number;
END;
$$ LANGUAGE plpgsql STABLE;


-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_type_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservation_guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE hotel_settings ENABLE ROW LEVEL SECURITY;

-- 1. Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can do everything on profiles" ON profiles
  FOR ALL USING (is_admin());

-- 2. Room Types Policies
CREATE POLICY "Room types are viewable by everyone" ON room_types
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage room types" ON room_types
  FOR ALL USING (is_admin());

-- 3. Rooms Policies
CREATE POLICY "Rooms are viewable by everyone" ON rooms
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage rooms" ON rooms
  FOR ALL USING (is_admin());

-- 4. Amenities Policies
CREATE POLICY "Amenities are viewable by everyone" ON amenities
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage amenities" ON amenities
  FOR ALL USING (is_admin());

-- 5. Room Type Amenities Policies
CREATE POLICY "Room type amenities are viewable by everyone" ON room_type_amenities
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage room type amenities" ON room_type_amenities
  FOR ALL USING (is_admin());

-- 6. Room Images Policies
CREATE POLICY "Room images are viewable by everyone" ON room_images
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage room images" ON room_images
  FOR ALL USING (is_admin());

-- 7. Reservations Policies
CREATE POLICY "Users can view their own reservations" ON reservations
  FOR SELECT USING (auth.uid() = user_id OR is_admin());

CREATE POLICY "Users can insert their own reservations" ON reservations
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can cancel or modify their own pending/confirmed reservations" ON reservations
  FOR UPDATE USING (auth.uid() = user_id OR is_admin());

-- 8. Reservation Guests Policies
CREATE POLICY "Users can view guest info for their own reservations" ON reservation_guests
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM reservations
      WHERE reservations.id = reservation_id AND (reservations.user_id = auth.uid() OR is_admin())
    )
  );

CREATE POLICY "Users can insert guest info for their own reservations" ON reservation_guests
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM reservations
      WHERE reservations.id = reservation_id AND reservations.user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage all guest info" ON reservation_guests
  FOR ALL USING (is_admin());

-- 9. Payments Policies
CREATE POLICY "Users can view payments for their own reservations" ON payments
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM reservations
      WHERE reservations.id = reservation_id AND (reservations.user_id = auth.uid() OR is_admin())
    )
  );

CREATE POLICY "Admins can manage all payments" ON payments
  FOR ALL USING (is_admin());

-- 10. Reviews Policies
CREATE POLICY "Reviews are viewable by everyone" ON reviews
  FOR SELECT USING (true);

CREATE POLICY "Users can insert reviews for completed stays" ON reviews
  FOR INSERT WITH CHECK (
    auth.uid() = user_id 
    AND EXISTS (
      -- Check that user actually stayed in this room type and status is checked_out
      SELECT 1 FROM reservations r
      JOIN rooms rm ON r.room_id = rm.id
      WHERE r.id = reservation_id 
        AND r.user_id = auth.uid() 
        AND rm.room_type_id = room_type_id
        AND r.status = 'checked_out'
    )
  );

CREATE POLICY "Users can update their own reviews" ON reviews
  FOR UPDATE USING (auth.uid() = user_id OR is_admin());

-- 11. Hotel Settings Policies
CREATE POLICY "Settings are viewable by everyone" ON hotel_settings
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage settings" ON hotel_settings
  FOR ALL USING (is_admin());


-- ============================================
-- SEED DATA
-- ============================================

-- Insert Amenities
INSERT INTO amenities (name, icon, category) VALUES
  ('Wi-Fi', 'Wifi', 'comfort'),
  ('TV', 'Tv', 'media'),
  ('Minibar', 'Wine', 'comfort'),
  ('Aire acondicionado', 'Snowflake', 'comfort'),
  ('Baño privado', 'Bath', 'comfort'),
  ('Balcón', 'DoorOpen', 'views'),
  ('Vista al mar', 'Waves', 'views'),
  ('Jacuzzi', 'Droplets', 'luxury'),
  ('Sala de estar', 'Sofa', 'comfort'),
  ('Caja fuerte', 'Lock', 'security'),
  ('Secador de pelo', 'Wind', 'comfort'),
  ('Servicio de habitaciones', 'ConciergeBell', 'service')
ON CONFLICT (name) DO NOTHING;

-- Insert Room Types and save UUIDs
INSERT INTO room_types (name, slug, description, base_price, capacity, size, beds) VALUES
  ('Standard Room', 'standard-room', 'Habitación acogedora con todas las comodidades esenciales, ideal para parejas.', 119.00, 2, 28.0, '1 cama Queen'),
  ('Deluxe Room', 'deluxe-room', 'Espacio elegante con cama King y amenidades de primera clase para una estancia de lujo.', 149.00, 2, 32.0, '1 cama King'),
  ('Suite Ocean View', 'suite-ocean-view', 'Suite espaciosa con una impresionante vista al mar, sala de estar y balcón privado.', 249.00, 3, 48.0, '1 cama King + sofá cama'),
  ('Presidential Suite', 'presidential-suite', 'La máxima experiencia de lujo. Amplia suite con dos camas King, jacuzzi privado frente al mar y servicio exclusivo.', 449.00, 4, 75.0, '2 camas King')
ON CONFLICT (name) DO NOTHING;

-- Associate Amenities with Room Types
-- (This can be run after room types are created to link them up)
INSERT INTO room_type_amenities (room_type_id, amenity_id)
SELECT rt.id, am.id
FROM room_types rt, amenities am
WHERE rt.slug = 'standard-room' AND am.name IN ('Wi-Fi', 'TV', 'Aire acondicionado', 'Baño privado', 'Caja fuerte', 'Secador de pelo')
ON CONFLICT DO NOTHING;

INSERT INTO room_type_amenities (room_type_id, amenity_id)
SELECT rt.id, am.id
FROM room_types rt, amenities am
WHERE rt.slug = 'deluxe-room' AND am.name IN ('Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones')
ON CONFLICT DO NOTHING;

INSERT INTO room_type_amenities (room_type_id, amenity_id)
SELECT rt.id, am.id
FROM room_types rt, amenities am
WHERE rt.slug = 'suite-ocean-view' AND am.name IN ('Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Balcón', 'Vista al mar', 'Sala de estar', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones')
ON CONFLICT DO NOTHING;

INSERT INTO room_type_amenities (room_type_id, amenity_id)
SELECT rt.id, am.id
FROM room_types rt, amenities am
WHERE rt.slug = 'presidential-suite' AND am.name IN ('Wi-Fi', 'TV', 'Minibar', 'Aire acondicionado', 'Baño privado', 'Balcón', 'Vista al mar', 'Jacuzzi', 'Sala de estar', 'Caja fuerte', 'Secador de pelo', 'Servicio de habitaciones')
ON CONFLICT DO NOTHING;

-- Insert Physical Rooms
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '101', 1, 'available' FROM room_types WHERE slug = 'standard-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '102', 1, 'available' FROM room_types WHERE slug = 'standard-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '103', 1, 'available' FROM room_types WHERE slug = 'standard-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '104', 1, 'maintenance' FROM room_types WHERE slug = 'standard-room' ON CONFLICT DO NOTHING;

INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '201', 2, 'available' FROM room_types WHERE slug = 'deluxe-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '202', 2, 'available' FROM room_types WHERE slug = 'deluxe-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '203', 2, 'available' FROM room_types WHERE slug = 'deluxe-room' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '204', 2, 'available' FROM room_types WHERE slug = 'deluxe-room' ON CONFLICT DO NOTHING;

INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '301', 3, 'available' FROM room_types WHERE slug = 'suite-ocean-view' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '302', 3, 'available' FROM room_types WHERE slug = 'suite-ocean-view' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '303', 3, 'available' FROM room_types WHERE slug = 'suite-ocean-view' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '304', 3, 'available' FROM room_types WHERE slug = 'suite-ocean-view' ON CONFLICT DO NOTHING;

INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '401', 4, 'available' FROM room_types WHERE slug = 'presidential-suite' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '402', 4, 'available' FROM room_types WHERE slug = 'presidential-suite' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '403', 4, 'available' FROM room_types WHERE slug = 'presidential-suite' ON CONFLICT DO NOTHING;
INSERT INTO rooms (room_type_id, room_number, floor, status)
SELECT id, '404', 4, 'available' FROM room_types WHERE slug = 'presidential-suite' ON CONFLICT DO NOTHING;
